DROP TABLE COMPANIES
GO
CREATE TABLE COMPANIES  ( 
	COMPANY_NAME_ID	INTEGER NOT NULL,
	COMPANY_ID     	INTEGER NULL,
	NAME           	TEXT NOT NULL,
	LOCALE         	TEXT NULL,
	NAME_TYPE      	TEXT NULL,
	CHANGESET_ID   	INTEGER NULL,
	ACTIVE         	INTEGER DEFAULT 'Y' NOT NULL 
	)
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(1000, 1000, 'LinkedI', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(1001, 1000, 'LinkedIn Corporatio', '*', 'ALTR', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(1002, 1001, 'IBM', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(1003, 1001, 'International Business Machines', '*', 'ALTR', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(1004, 1001, 'Big Blue', '*', 'ALTR', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(2000, 2000, 'Tivoli', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(2001, 2001, 'Rational', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(1005, 1002, 'General Electric', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(1006, 1002, 'GE', '*', 'ALTR', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(3000, 3000, 'eBay', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(3001, 3001, 'PayPal', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(1007, 1003, 'Genentech', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(1008, 1004, 'Pfizer', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(1009, 1005, 'Apple', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(1010, 1006, 'NASA', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(1011, 1006, 'National Aeronautics and Space Administratio', '*', 'ALTR', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(1012, 1007, 'Pixar', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(1013, 1008, 'Apple Corps', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(1014, 1008, 'Apple Records', '*', 'ALTR', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(1015, 1008, 'Apple', '*', 'ALTR', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(1016, 1009, 'Microsoft, Inc.', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(1017, 1010, 'Sun Microsystems', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(1018, 1011, 'Barnes and Noble', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(1019, 1012, 'The Home Depot', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11013, 11013, 'Ericsso', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11014, 11014, 'Sun Microsystems', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11015, 11015, 'Cisco Systems', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11016, 11016, 'Motorola', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11017, 11017, 'JPMorgan Chase', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11018, 11018, 'Nokia', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11019, 11019, 'Ernst & Young', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11020, 11020, 'Capgemini', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11021, 11021, 'KPMG', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11022, 11022, 'Philips', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11023, 11023, 'Nortel Networks', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11024, 11024, 'Dell', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11025, 11025, 'Verizo', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11026, 11026, 'Sprint Nextel', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11027, 11027, 'SAP', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11028, 11028, 'Procter & Gamble', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11029, 11029, 'CSC', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11030, 11030, 'Bank of America', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11031, 11031, 'EMC', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11032, 11032, 'ABN AMRO', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11033, 11033, 'Merrill Lynch', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11034, 11034, 'BT', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11035, 11035, 'Pfizer', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11036, 11036, 'Johnson & Johnso', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11037, 11037, 'ING', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11038, 11038, 'UBS', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11039, 11039, 'Vodafone', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11040, 11040, 'Symantec', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11041, 11041, 'Wells Fargo', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11042, 11042, 'HSBC', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11043, 11043, 'Unilever', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11044, 11044, 'Sony', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11045, 11045, 'AOL', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11046, 11046, 'Atos Origi', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11047, 11047, 'Deutsche Bank', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11048, 11048, 'LogicaCMG', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11049, 11049, 'Shell', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11050, 11050, 'Apple Computer', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11051, 11051, 'American Express', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11052, 11052, 'Unisys', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11053, 11053, 'Infosys', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11054, 11054, 'Credit Suisse', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11055, 11055, 'Yahoo!', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11056, 11056, 'The Walt Disney Company', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11057, 11057, 'Fidelity Investments', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11058, 11058, 'Wipro Technologies', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11059, 11059, 'Lockheed Marti', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11060, 11060, 'US Navy', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11061, 11061, 'Honeywell', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11062, 11062, 'BearingPoint', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11063, 11063, 'Morgan Stanley', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11064, 11064, 'Tata Consultancy Services', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11065, 11065, 'DHL', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11066, 11066, 'National Security Agency', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11067, 11067, 'National Westminster Bank', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11068, 11068, 'National Health Service', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11069, 11069, 'National Computer Systems', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11070, 11070, 'National Steel Corporatio', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11071, 11071, 'National Broadcasting Company', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11072, 11072, 'National Guard Bureau', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11073, 11073, 'National Informatics Center', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11074, 11074, 'National Blood Service', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11075, 11075, 'National TechTeam', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11076, 11076, 'National Computer Board', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11077, 11077, 'National Agents Alliance', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11078, 11078, 'National Center for Supercomputing Applications', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11079, 11079, 'National Data Corporatio', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11080, 11080, 'McKinsey & Company', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11081, 11081, 'Computer Associates', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11082, 11082, 'Xerox', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11083, 11083, 'Fujitsu', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11084, 11084, 'Goldman Sachs', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11085, 11085, 'Boeing', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11086, 11086, 'BP', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11087, 11087, 'T-Mobile', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11088, 11088, 'Nestle', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11089, 11089, 'Texas Instruments', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11090, 11090, 'GlaxoSmithKline', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11091, 11091, 'Reuters', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11092, 11092, 'Booz Allen Hamilto', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11093, 11093, 'Novartis', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11094, 11094, 'Wachovia', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11095, 11095, 'Northrop Grumma', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11096, 11096, 'CGI', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11097, 11097, 'Capital One', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11098, 11098, 'Barclays', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11099, 11099, 'Getronics', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11100, 11100, 'PepsiCo', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11101, 11101, 'Arthur Anderse', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11102, 11102, 'Google', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11103, 11103, 'KP', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11104, 11104, 'Electronic Arts', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11105, 11105, 'Novell', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11106, 11106, 'ADP', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11107, 11107, 'Washington Mutual', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11108, 11108, 'Lehman Brothers', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11109, 11109, 'NCR', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11110, 11110, 'Schlumberger', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11111, 11111, 'General Motors', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11112, 11112, 'Cable & Wireless', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11113, 11113, 'Adobe Systems', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11114, 11114, 'eBay', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11115, 11115, 'Ford Motor Company', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11116, 11116, 'Merck', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11117, 11117, 'ABB', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11118, 11118, 'SAS', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11119, 11119, 'Avaya', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11120, 11023, 'Nortel', '*', 'ALTR', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11121, 11026, 'Sprint', '*', 'ALTR', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11122, 11045, 'America Online', '*', 'ALTR', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11123, 11036, 'J&J', '*', 'ALTR', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11124, 11051, 'Amex', '*', 'ALTR', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11125, 11053, 'Infosys Technologies Ltd', '*', 'ALTR', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11130, 11104, 'EA', '*', 'ALTR', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11131, 11107, 'WaMu', '*', 'ALTR', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11132, 11116, 'MSD', '*', 'ALTR', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11133, 11116, 'Merck Sharp & Dohme', '*', 'ALTR', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11134, 11064, 'TCS', '*', 'ALTR', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11135, 11086, 'British Petroleum', '*', 'ALTR', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11136, 11089, 'TI', '*', 'ALTR', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11137, 11120, 'IBM Global Services', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11138, 11121, 'Rational Software', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11139, 11122, 'PureAtria', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11140, 11123, 'Unicible', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11141, 11124, 'LGS Group', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11142, 11125, 'Informix Software', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11143, 11126, 'GE Healthcare', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11144, 11127, 'GE Capital', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11145, 11128, 'GE Money', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11146, 11129, 'GE Plastics', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11147, 11130, 'GE Money Bank', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11148, 11131, 'VisioWave', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11149, 11132, 'GE Commercial Finance', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11150, 11133, 'IDX Systems', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11151, 11134, 'Amersham Biosciences', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11152, 11135, 'Amersham Health', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11153, 11136, 'Nuovo Pignone', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11154, 11137, 'GE Energy', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11155, 11138, 'HP Software', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11156, 11139, 'Hewlett-Packard Laboratories', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11157, 11140, 'Hewlett-Packard Financial Services', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11158, 11141, 'PeopleSoft', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11159, 11142, 'Siebel Systems', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11160, 11143, '360Commerce', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11161, 11144, 'ProfitLogic', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11162, 11145, 'Accenture Technology Solutions', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11163, 11146, 'MS', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11164, 11147, 'Ensemble Studios', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11165, 11148, 'Touche Ross', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11166, 11149, 'Deloitte Consulting', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11167, 11150, 'PwC Consulting', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11168, 11151, 'Cingular Wireless', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11169, 11152, 'AT&T Wireless', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11170, 11153, 'SBC', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11171, 11154, 'Cingular', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11172, 11155, 'Intel Capital', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11173, 11156, 'Lucent Technologies', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11174, 11157, 'Bell Labs', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11175, 11158, 'Newbridge Networks', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11176, 11159, 'Alcatel', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11177, 11160, 'Hutchison Telecoms', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11178, 11161, 'Marconi', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11179, 11162, 'Linksys', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11180, 11163, 'Motorola Mobile Devices', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11181, 11164, 'Motorola India', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11182, 11165, 'JPMorga', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11183, 11166, 'Nokia Mobile Phones', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11184, 11167, 'Nokia Siemens Networks', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11185, 11168, 'Ernst & Young Consulting', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11186, 11169, 'Cap Gemini Ernst & Young', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11187, 11170, 'Capgemini Consulting', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11188, 11171, 'Cap Gemini Sogeti', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11189, 11172, 'KPMG Peat Marwick', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11190, 11173, 'KPMG Corporate Finance', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11191, 11174, 'KPMG Advisory', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11192, 11175, 'KPMG Audit', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11193, 11176, 'NXP Semiconductors', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11194, 11177, 'Philips Medical Systems', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11195, 11178, 'Philips Consumer Electronics', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11196, 11179, 'Lumileds Lighting', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11197, 11180, 'NXP Software', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11198, 11181, 'Assembleo', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11199, 11182, 'Philips Research', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11200, 11183, 'Philips Lighting', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11201, 11184, 'Verizon Business', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11202, 11185, 'Verizon Data Services', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11203, 11186, 'Verizon Yellow Pages', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11204, 11187, 'Verizon Labs', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11205, 11188, 'Verizon Enterprise Solutions Group', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11206, 11189, 'Verizon Federal', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11207, 11190, 'Verizon Avenue', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11208, 11191, 'Verizon Airfone', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11209, 11192, 'Nextel Partners', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11210, 11193, 'Nextel', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11211, 11194, 'SAP Labs', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11212, 11195, 'P&G Pharmaceuticals', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11213, 11196, 'Duracell', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11214, 11197, 'Gillette', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11215, 11198, 'PMSC', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11216, 11199, 'CSC Consulting', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11217, 11200, 'MBNA', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11218, 11201, 'Banc of America Securities', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11219, 11202, 'Fleet Bank', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11220, 11203, 'Banc of America Investments', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11221, 11204, 'Legato Systems', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11222, 11205, 'EMC Computer Systems', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11223, 11206, 'Documentum', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11224, 11207, 'Interlink', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11225, 11208, 'SMARTS', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11226, 11209, 'Internosis', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11227, 11210, 'Captiva Software', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11228, 11211, 'LaSalle Bank Corporatio', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11229, 11212, 'LaSalle Bank', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11230, 11213, 'Banco Real', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11231, 11214, 'Standard Federal Bank', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11232, 11215, 'Merrill Lynch Investment Managers', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11233, 11216, 'BT Wholesale', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11234, 11217, 'BT Global Services', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11235, 11218, 'Atlanet', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11236, 11219, 'Albacom', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11237, 11220, 'Pfizer Pharmaceuticals', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11238, 11221, 'Pfizer Consumer Healthcare', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11239, 11222, 'PGRD', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11240, 11223, 'DePuy Mitek', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11241, 11224, 'McNeil Nutritionals', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11242, 11225, 'DePuy Orthopaedics', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11243, 11226, 'Tibotec', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11244, 11227, 'Vistako', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11245, 11228, 'Biosense Webster', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11246, 11229, 'Neutrogena', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11247, 11230, 'Ortho Clinical Diagnostics', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11248, 11231, 'Ortho Biotech', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11249, 11232, 'Cordis', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11250, 11233, 'McNeil Consumer Healthcare', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11251, 11234, 'ALZA Corporatio', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11252, 11235, 'Ethicon Endo-Surgery', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11253, 11236, 'LifeSca', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11254, 11237, 'Janssen-Cilag', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11255, 11238, 'Janssen-Ortho', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11256, 11239, 'Centocor', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11257, 11240, 'Ethico', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11258, 11241, 'Nationale Nederlande', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11259, 11242, 'Postbank', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11260, 11243, 'UBS Global Asset Management', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11261, 11244, 'UBS Wealth Management', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11262, 11245, 'UBS Investment Bank', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11263, 11246, 'Connex', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11264, 11247, 'Oskar', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11265, 11248, 'Telsim', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11266, 11249, 'Mobifon SA', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11267, 11250, 'Libertel', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11268, 11251, 'Altiris', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11269, 11252, 'VERITAS Software', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11270, 11253, 'Seagate Software', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11271, 11254, 'Wells Fargo Bank', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11272, 11255, 'Wells Fargo Home Mortgage', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11273, 11256, 'Wells Fargo Financial', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11274, 11257, 'Wells Fargo Investments', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11275, 11258, 'Wells Capital Management', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11276, 11259, 'Household Credit Services', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11277, 11260, 'CCF', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11278, 11261, 'Household International', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11279, 11262, 'HSBC Card Services', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11280, 11263, 'Metris Companies', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11281, 11264, 'HSBC Securities', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11282, 11265, 'Unilever Bestfoods', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11283, 11266, 'Unilever HPC', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11284, 11267, 'Sony Computer Entertainment America', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11285, 11268, 'Sony Online Entertainment', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11286, 11269, 'Sony Electronics', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11287, 11270, 'Sony Pictures Entertainment', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11288, 11271, 'AOL Time Warner', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11289, 11272, 'Atos Worldline', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11290, 11273, 'Atos Consulting', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11291, 11274, 'DWS Investments', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11292, 11275, 'Deutsche Bank Securities', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11293, 11276, 'Deutsche Asset Management', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11294, 11277, 'UFG', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11295, 11278, 'Acisio', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11296, 11279, 'ACE', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11297, 11280, 'Edinfor', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11298, 11281, 'Shell Oil Company', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11299, 11282, 'Shell Global Solutions', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11300, 11283, 'Shell Trading', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11301, 11284, 'Apple Retail', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11302, 11285, 'American Express Financial Advisors', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11303, 11286, 'American Express Business Travel', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11304, 11287, 'American Express Bank', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11305, 11288, 'iPSL', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11306, 11289, 'Credit Suisse First Bosto', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11307, 11290, 'Yahoo! Search Marketing', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11308, 11291, 'HotJobs.com', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11309, 11292, 'Musicmatch', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11310, 11293, 'Overture', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11311, 11294, 'Disney Vacation Club', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11312, 11295, 'Disneyland', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11313, 11296, 'Disney ABC Television Group', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11314, 11297, 'Disney Channel', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11315, 11298, 'Disney Publishing Worldwide', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11316, 11299, 'Disney Consumer Products', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11317, 11300, 'Disney Mobile', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11318, 11301, 'Disney Cruise Line', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11319, 11302, 'Disney Direct Marketing', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11320, 11303, 'Disneyland Resort', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11321, 11304, 'Walt Disney Imagineering', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11322, 11305, 'Walt Disney Feature Animatio', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11323, 11306, 'Walt Disney Internet Group', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11324, 11307, 'Disney Interactive Studios', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11325, 11308, 'Veritude', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11326, 11309, 'FMR', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11327, 11310, 'Fidelity Capital Markets', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11328, 11311, 'National Financial', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11329, 11312, 'J. Robert Scott', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11330, 11313, 'Fidelity Ventures', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11331, 11314, 'Wipro BPO', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11332, 11315, 'Wipro Spectramind', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11333, 11316, 'Wipro Infotech Ltd', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11334, 11317, 'Wipro Consulting', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11335, 11318, 'Lockheed Martin Space Systems Company', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11336, 11319, 'Lockheed Martin Aeronautics', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11337, 11320, 'Naval Research Laboratory', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11338, 11321, 'SPAWAR', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11339, 11322, 'NAVAIR', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11340, 11323, 'Naval Surface Warfare Center', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11341, 11324, 'Naval Undersea Warfare Center', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11342, 11325, 'Naval Air Systems Command', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11343, 11326, 'Naval War College', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11344, 11327, 'Puget Sound Naval Shipyard', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11345, 11328, 'Norfolk Naval Shipyard', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11346, 11329, 'Office of Naval Intelligence', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11347, 11330, 'Portsmouth Naval Shipyard', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11348, 11331, 'U.S. Navy Reserve', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11349, 11332, 'Military Sealift Command', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11350, 11333, 'Naval Sea Systems Command', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11351, 11334, 'Honeywell Aerospace', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11352, 11335, 'Honeywell Process Solutions', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11353, 11336, 'Honeywell Information Systems', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11354, 11337, 'HTSL', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11355, 11338, 'BearingPoint Consulting', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11356, 11339, 'Morgan Stanley Investment Management', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11357, 11340, 'DHL Aviatio', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11358, 11341, 'Airborne Express', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11359, 11342, 'Fujitsu Services', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11360, 11343, 'Fujitsu Consulting', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11361, 11344, 'Fujitsu Network Communications', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11362, 11345, 'Wi-LAN Inc.', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11363, 11346, 'Goldman Sachs Asset Management', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11364, 11347, 'Boeing Commercial Airplanes', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11365, 11348, 'Connexion by Boeing', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11366, 11349, 'Boeing Satellite Systems', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11367, 11350, 'BP Amoco', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11368, 11351, 'BP Chemicals', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11369, 11352, 'Castrol', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11370, 11353, 'Nestle Purina', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11371, 11354, 'Nestlv© Nutritio', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11372, 11355, 'Nestle Waters', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11373, 11356, 'SmithKline Beecham', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11374, 11357, 'Lipper', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11375, 11358, 'Reuters Financial Software', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11376, 11359, 'Novartis Consumer Health', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11377, 11360, 'Chiron Corporatio', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11378, 11361, 'World Savings', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11379, 11362, 'Wachovia Bank', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11380, 11363, 'Palmer & Cay', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11381, 11364, 'Wachovia Securities', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11382, 11365, 'Northrop Grumman Mission Systems', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11383, 11366, 'Northrop Grumman Space Technology', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11384, 11367, 'AMS', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11385, 11368, 'CGI-AMS', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11386, 11369, 'CGI Federal', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11387, 11370, 'Capital One Auto Finance', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11388, 11371, 'Barclays Stockbrokers', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11389, 11372, 'Barclays Capital', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11390, 11373, 'Barclays Wealth', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11391, 11374, 'Barclaycard', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11392, 11375, 'Barclays Bank', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11393, 11376, 'Getronics PinkRoccade', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11394, 11377, 'PinkRoccade IT Management', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11395, 11378, 'PinkRoccade', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11396, 11379, 'Pepsi Bottling Group', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11397, 11380, 'Frito Lay', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11398, 11381, 'Quaker Oats', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11399, 11382, 'Walkers', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11400, 11383, 'Sabritas', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11401, 11384, 'QTG', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11402, 11385, 'Gatorade', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11403, 11386, 'Tropicana', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11404, 11387, 'KPN Telecom', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11405, 11388, 'KPN Mobile', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11406, 11389, 'Sympac', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11407, 11390, 'KPN Internet', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11408, 11391, 'KPN Orange', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11409, 11392, 'KPN Research', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11410, 11393, 'Maxis', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11411, 11394, 'EA Mobile', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11412, 11395, 'Criterion Games', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11413, 11396, 'Mythic Entertainment', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11414, 11397, 'EA Mythic', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11415, 11398, 'SUSE Linux AG', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11416, 11399, 'Cambridge Technology Partners', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11417, 11400, 'ProBusiness', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11418, 11401, 'Providian Financial', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11419, 11402, 'Washington Mutual Card Services', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11420, 11403, 'ADP Dealer Services', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11421, 11404, 'ADP TotalSource', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11422, 11405, 'Teradata', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11423, 11406, 'WesternGeco', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11424, 11407, 'Schlumberger Information Solutions', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11425, 11408, 'Schlumberger Technologies', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11426, 11409, 'GMTV', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11427, 11410, 'GMAC', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11428, 11411, 'Energis', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11429, 11412, 'WTG', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11430, 11413, 'GTS', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11431, 11414, 'Macromedia', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11432, 11415, 'PayPal', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11433, 11416, 'Ford Motor Credit Company', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11434, 11417, 'Merck KGaA', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11435, 11418, 'Rosetta Inpharmatics', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11436, 11419, 'ABB Corporate Research', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11437, 11420, 'ABB Lummus Global', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11438, 11421, 'Scandinavian IT Group', '*', 'CNCL', NULL, 'Y')
GO
INSERT INTO COMPANIES(COMPANY_NAME_ID, COMPANY_ID, NAME, LOCALE, NAME_TYPE, CHANGESET_ID, ACTIVE)
  VALUES(11439, 11422, 'Tenovis', '*', 'CNCL', NULL, 'Y')
GO
